// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBJaQvXtMt2bC2Bua5ksE89-LaYFJiktg',
    appId: '1:260190089217:web:4817e7b553c14abed59000',
    messagingSenderId: '260190089217',
    projectId: 'estateease',
    authDomain: 'estateease.firebaseapp.com',
    storageBucket: 'estateease.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzn7u0cX98zQwRUep1bQg10M1GNNig_e8',
    appId: '1:260190089217:android:0db76442229a955bd59000',
    messagingSenderId: '260190089217',
    projectId: 'estateease',
    storageBucket: 'estateease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ow7lAQ6qDWchr1nB655cPxKnq4Mn29U',
    appId: '1:260190089217:ios:f6f47e228dca621ad59000',
    messagingSenderId: '260190089217',
    projectId: 'estateease',
    storageBucket: 'estateease.appspot.com',
    iosClientId: '260190089217-v9c5t4imdindq5in3j714orjargidjp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.estateease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ow7lAQ6qDWchr1nB655cPxKnq4Mn29U',
    appId: '1:260190089217:ios:879ff17c443eaf7ad59000',
    messagingSenderId: '260190089217',
    projectId: 'estateease',
    storageBucket: 'estateease.appspot.com',
    iosClientId: '260190089217-5ntk0nhi6paqpksfgpub9oraikqfiil2.apps.googleusercontent.com',
    iosBundleId: 'com.example.estateease.RunnerTests',
  );
}
